image: proboci/ubuntu-14.04-lamp:php7.0-nightly
assets:
  - d8testsite.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    database: d8testsite.sql.gz
    databaseGzipped: true
  - name: Generate login link
    command: "drush --root='/var/www/html/' uli"
