phpIniOptions:
  upload_max_filesize: 25M
  post_max_size: 25M
  memory_limit: 256M

mysqlIniOptions:
  innodb_file_per_table=OFF
  
steps:
  - name: Check wp-cli version.
    plugin: Script
    script:
      - wp --info --allow-root
