image: proboci/ubuntu-16.04-lamp:php7.2-nightly
steps:
  - name: Probo site setup
    plugin: Drupal
    database: drupal_github.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    revertFeatures: true
    clearCaches: true
