steps:
  - name: Say hello
    plugin: Script
    script:
      - echo "Hello, world!"
  - name: Loop
    plugin: Script
    script:
      - for i in {1...5} ; do echo "Looping ... number $i" && sleep 5 ; done
