steps:
  - name: Checking ubuntu, apache, mysql, and php version.
    plugin: Script
    script:
      - lsb_release -a
      - mysql --version
      - apache2 -version
      - php -v
  - name: Checking installed software and tools.
    plugin: Script
    script:
      - node -v
      - composer --version
      - wp --info --allow-root 
