steps:
  - name: Say hello
    plugin: Script
    script:
      - echo "Hello, world!"
  - name: Create index.html
    plugin: Script
    script:
      - touch index.html
      - echo "<h1>Hello, World!</h1>" > index.html
