image: proboci/ubuntu-14.04-lamp:php-5.6
steps:
  - name: Check wp-cli version.
    plugin: Script
    script: |
      wp --info --allow-root
      ls -la /var/log
      php -v
  - name: Create index.html
    plugin: Script
    script: |
      echo 'testing this' >> /src/index.html
      ln -s /src /var/www/html
